-- ====================================================================
-- 0. STRIPE BILLING DATA VIEW (FOR INTERNAL AUDIT & DEBUGGING)
-- ====================================================================

create schema if not exists billing;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'stripe') THEN
    -- FIX: Needed to make stripe sync engine webhook's work
    ALTER TABLE "stripe"."charges" 
    ADD CONSTRAINT charges_id_unique UNIQUE ("id");
END IF; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'stripe') THEN
    create or replace view billing.user_charges as
    select
    u.email,
    u.id as user_id,
    customers.id as customer_id,
    customers.name as stripe_name,
    customers.tax_exempt,
    to_timestamp(charges.created)::timestamp at time zone 'UTC' as charged_at,
    charges.paid as charge_paid,
    charges.amount as charge_amount,
    charges.amount_refunded as charge_amount_refunded,
    charges.refunded as charge_refunded,
    charges.disputed as charge_disputed,
    charges.status as charge_status,
    subscriptions.status as sub_status,
    to_timestamp(subscriptions.canceled_at)::timestamp at time zone 'UTC' as sub_canceled_at,
    to_timestamp(subscriptions.ended_at)::timestamp at time zone 'UTC' as sub_ended_at,
    CASE 
        WHEN subscriptions.status IS NULL THEN 'once' ELSE 'subscription'
    END AS effective_charge_type,
    CASE 
        WHEN subscriptions.canceled_at IS NULL AND subscriptions.status = 'active' THEN 'active'
        WHEN subscriptions.ended_at IS NULL AND subscriptions.cancel_at_period_end IS FALSE THEN 'canceled_before_sub_end' 
        WHEN subscriptions.ended_at IS NULL AND subscriptions.cancel_at_period_end IS TRUE THEN 'canceled_at_sub_end'
        WHEN subscriptions.ended_at IS NOT NULL THEN 'ended'
        ELSE subscriptions.status
    END as effective_sub_status,
    CASE 
        WHEN charges.paid is true and charges.refunded is false and charges.disputed is false and charges.status = 'succeeded' THEN charges.amount - charges.amount_refunded
        ELSE 0
    END as effective_charge_amount,
    to_timestamp(charges.created)::timestamp at time zone 'UTC' + interval '1 year' as effective_charge_expires_at
    from
    stripe.charges charges
    join stripe.customers customers on charges.billing_details->>'email' = customers.email
    left join (
        select * from stripe.subscriptions s
        order by start_date desc limit 1
        ) subscriptions on customers.id = subscriptions.customer and charges.customer is not null
    join auth.users u on customers.email = u.email;
END IF; END $$;


-- ====================================================================
-- 1. SCHEMA INITIALIZATION & TYPE DEFINITIONS
-- ====================================================================

CREATE TYPE "public"."credit_type" AS ENUM('private', 'public');

CREATE TYPE "public"."credit_source" AS ENUM('stripe_charge', 'consumed', 'expired_consumed', 'expired_to_public');


-- ====================================================================
-- 2. TABLES DESIGN
-- ====================================================================

-- Rules determining how many credits are granted per currency unit
create table if not exists billing.credit_conversion_rules (
  id bigint generated always as identity primary key,
  currency text unique not null, -- lowercase currency code (e.g. 'eur', 'usd')
  private_credits_per_unit numeric not null default 20.0,
  public_credits_per_unit numeric not null default 10.0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- The append-only source of truth ledger
create table if not exists public.credit_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete set null, -- NULL represent public pool entries
  credit_type public.credit_type not null,
  amount integer not null, -- Positive for additions, negative for consumptions/expirations
  source public.credit_source not null,
  stripe_charge_id text, -- Populated if generated by a Stripe Sync Engine event
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indices to accelerate audit history scans and balance calculations
create index if not exists idx_credit_logs_user_type on public.credit_logs(user_id, credit_type);
create index if not exists idx_credit_logs_created_at on public.credit_logs(created_at);
create index if not exists idx_credit_logs_stripe_charge on public.credit_logs(stripe_charge_id) where stripe_charge_id is not null;

-- Live aggregate balance table managed completely by triggers
create table if not exists public.credit_balances (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade, -- NULL represents the shared public pool
  balance integer not null default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Complete structural data integrity constraints for credit_balances:
-- Exactly 1 public pool row allowed, maximum 1 private row per user.
create unique index if not exists unique_public_balance_row 
  on public.credit_balances ((user_id is null)) 
  where user_id is null;

create unique index if not exists unique_user_private_balance_row 
  on public.credit_balances (user_id) 
  where user_id is not null;

-- FIX: Needed to make stripe sync engine webhook's work
CREATE UNIQUE INDEX IF NOT EXISTS credit_balances_user_id_idx 
ON public.credit_balances (user_id) NULLS NOT DISTINCT;

-- Ensure public pool exists right out of the gate
insert into public.credit_balances (user_id, balance) 
values (null, 0) 
on conflict do nothing;


-- ====================================================================
-- 3. CORE AUTOMATION TRIGGERS (LOG TO BALANCE AGGREGATION)
-- ====================================================================

create or replace function billing.on_credit_log_insert_update_balances()
returns trigger as $$
begin
  if new.user_id is null then
    -- Route to the global public pool row
    update public.credit_balances
    set balance = balance + new.amount,
        updated_at = timezone('utc'::text, now())
    where user_id is null;
  else
    -- Route to or create the unique private user balance row
    insert into public.credit_balances (user_id, balance, updated_at)
    values (new.user_id, new.amount, timezone('utc'::text, now()))
    on conflict (user_id) do update 
    set balance = public.credit_balances.balance + excluded.balance,
        updated_at = timezone('utc'::text, now());
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger trigger_on_credit_log_insert_update_balances
  after insert on public.credit_logs
  for each row
  execute function billing.on_credit_log_insert_update_balances();


-- ====================================================================
-- 4. STRIPE INGESTION ENGINE (STRIPE TO LEDGER PIPELINE)
-- ====================================================================

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'stripe') THEN
    EXECUTE '
    create or replace function billing.on_stripe_charge_insert_append_credit_log()
    returns trigger as $f$
    declare
    v_user_id uuid;
    v_private_rule numeric;
    v_public_rule numeric;
    v_amount_currency numeric;
    v_private_credits integer;
    v_public_credits integer;
    begin
    -- Only execute on successful, fully processed transactions
    if (new.paid = true and new.status = ''succeeded'') then
        
        -- Idempotency protection check
        if exists (select 1 from public.credit_logs where stripe_charge_id = new.id) then
        return new;
        end if;

        -- Look up the auth user mapped to the customer email inside Stripe Engine
        select u.id into v_user_id
        from auth.users u
        where u.email = new.billing_details->>''email''
        limit 1;

        if v_user_id is null and new.customer is not null then
        select u.id into v_user_id
        from stripe.customers c
        join auth.users u on c.email = u.email
        where c.id = new.customer
        limit 1;
        end if;

        -- Skip processing if charge cannot be associated with a registered app user
        if v_user_id is null then
        return new;
        end if;

        -- Fetch conversion factors based on currency
        select private_credits_per_unit, public_credits_per_unit
        into v_private_rule, v_public_rule
        from billing.credit_conversion_rules
        where currency = lower(new.currency);

        -- Fallback default values if rule row is not explicitly matching
        if not found then
        v_private_rule := 20.0;
        v_public_rule := 10.0;
        end if;

        -- Stripe amounts are provided in minor units (cents). Convert to standard units.
        v_amount_currency := new.amount / 100.0;
        v_private_credits := floor(v_amount_currency * v_private_rule);
        v_public_credits  := floor(v_amount_currency * v_public_rule);

        -- Append private entry to ledger
        if v_private_credits > 0 then
        insert into public.credit_logs (user_id, credit_type, amount, source, stripe_charge_id, metadata)
        values (
            v_user_id, 
            ''private'', 
            v_private_credits, 
            ''stripe_charge'', 
            new.id, 
            jsonb_build_object(''stripe_amount'', new.amount, ''currency'', new.currency)
        );
        end if;

        -- Append public community pool entry to ledger
        if v_public_credits > 0 then
        insert into public.credit_logs (user_id, credit_type, amount, source, stripe_charge_id, metadata)
        values (
            null, 
            ''public'', 
            v_public_credits, 
            ''stripe_charge'', 
            new.id, 
            jsonb_build_object(''stripe_amount'', new.amount, ''currency'', new.currency, ''sponsored_by'', v_user_id)
        );
        end if;

    end if;
    return new;
    end;
    $f$ language plpgsql security definer;
    ';
END IF; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'stripe') THEN
    -- Bind the trigger directly to your stripe.charges synced structure
    create trigger trigger_on_stripe_charge_insert_append_credit_log
    after insert or update on stripe.charges
    for each row
    execute function billing.on_stripe_charge_insert_append_credit_log();
END IF; END $$;


-- ====================================================================
-- 5. THE EXPIRATION CRON ENGINE (STATELESS MATHEMATICAL FIFO)
-- ====================================================================

create or replace function billing.process_expired_credits()
returns void as $$
declare
  r record;
begin
  -- For each user, we determine the amount that should be expired right now.
  -- target_to_expire = Total additions that are older than 12 months - Total lifetime consumptions.
  -- net_needed_now   = target_to_expire - Total amount already marked as expired historically.
  for r in (
    with user_ledger_summary as (
      select
        user_id,
        coalesce(sum(amount) filter (where amount > 0 and source = 'stripe_charge' and created_at <= now() - interval '12 months'), 0) as total_expired_window_grants,
        coalesce(sum(abs(amount)) filter (where amount < 0 and source = 'consumed' and credit_type = 'private'), 0) as total_lifetime_consumptions,
        coalesce(sum(abs(amount)) filter (where amount < 0 and source = 'expired_consumed' and credit_type = 'private'), 0) as total_already_expired
      from public.credit_logs
      where user_id is not null
      group by user_id
    ),
    calculated_expirations as (
      select
        user_id,
        greatest(0, total_expired_window_grants - total_lifetime_consumptions) as target_expired,
        total_already_expired
      from user_ledger_summary    
    )
    select 
      user_id, 
      (target_expired - total_already_expired) as net_credits_to_expire
    from calculated_expirations
    where (target_expired - total_already_expired) > 0
  ) loop
    
    -- Deduct from user's private credits
    insert into public.credit_logs (user_id, credit_type, amount, source, metadata)
    values (
      r.user_id, 
      'private', 
      -r.net_credits_to_expire, 
      'expired_consumed', 
      jsonb_build_object('expiry_execution_time', now())
    );

    -- Transfer matching value into the community public pool as a donation
    insert into public.credit_logs (user_id, credit_type, amount, source, metadata)
    values (
      null, 
      'public', 
      r.net_credits_to_expire, 
      'expired_to_public', 
      jsonb_build_object('origin_user_id', r.user_id, 'reason', '12-month timeline shift')
    );

  end loop;
end;
$$ language plpgsql security definer;


-- ====================================================================
-- 6. APPLICATION CONSUMPTION INTERFACE
-- ====================================================================

create or replace function public.consume_credits(
  p_user_id uuid,
  p_amount_to_consume integer,
  p_source text,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  private_credits_consumed integer,
  public_credits_consumed integer
) as $$
declare
  v_private_bal integer := 0;
  v_public_bal integer := 0;
  v_deduct_private integer := 0;
  v_deduct_public integer := 0;
begin
  -- 1. Input Sanity Check
  if p_amount_to_consume <= 0 then
    raise exception 'Consumption amount must be a positive integer value.';
  end if;

  -- 1b. Normalize p_metadata so the '||' merges below always yield a single flat
  -- object. PostgREST clients may send the metadata either as a proper jsonb
  -- object or as a JSON-encoded string (e.g. pre-JSON.stringify'd in the app).
  if p_metadata is not null and jsonb_typeof(p_metadata) = 'string' then
    p_metadata := (p_metadata #>> '{}')::jsonb;
  end if;

  -- 2. Lock and Read Private Balance to prevent race conditions
  -- (Assuming a row always exists per user. If not, consider a FOR UPDATE on a parent table or upsert)
  select coalesce(balance, 0) into v_private_bal
  from public.credit_balances
  where user_id = p_user_id
  for update; 

  -- If no row exists for the user, v_private_bal remains 0
  if v_private_bal is null then
    v_private_bal := 0;
  end if;

  -- 3. Calculate Private vs Public distribution
  if v_private_bal > 0 then
    if v_private_bal >= p_amount_to_consume then
      v_deduct_private := p_amount_to_consume;
    else
      v_deduct_private := v_private_bal;
      v_deduct_public  := p_amount_to_consume - v_private_bal;
    end if;
  else
    v_deduct_public := p_amount_to_consume;
  end if;

  -- 4. Process Public Pool Deductions with Lock
  if v_deduct_public > 0 then
    -- Lock the global shared row specifically to prevent double-spending from the public pool
    select coalesce(balance, 0) into v_public_bal
    from public.credit_balances
    where user_id is null
    for update;

    if v_public_bal < v_deduct_public then
      raise exception 'Action rejected. Insufficient credits in both private and shared community pools.';
    end if;
    
    -- Insert Public Log
    insert into public.credit_logs (user_id, credit_type, amount, source, metadata)
    values (
      null, 
      'public', 
      -v_deduct_public, 
      'consumed', 
      p_metadata || jsonb_build_object('billing_action_source', p_source, 'consumed_by_user_id', p_user_id)
    );
  end if;

  -- 5. Process Private Log Insertion
  if v_deduct_private > 0 then
    insert into public.credit_logs (user_id, credit_type, amount, source, metadata)
    values (
      p_user_id, 
      'private', 
      -v_deduct_private, 
      'consumed', 
      p_metadata || jsonb_build_object('billing_action_source', p_source)
    );
  end if;

  -- 6. Return the breakdown to the application
  private_credits_consumed := v_deduct_private;
  public_credits_consumed  := v_deduct_public;
  return next;
end;
$$ language plpgsql security definer;


-- ====================================================================
-- 7. ROW-LEVEL SECURITY (RLS)
-- ====================================================================

alter table public.credit_balances enable row level security;
alter table public.credit_logs enable row level security;
alter table billing.credit_conversion_rules enable row level security;

-- Client-side users read access constraints
create policy "select_own_balance" 
on public.credit_balances
for select 
using (auth.uid() = user_id);

create policy "select_own_logs" 
on public.credit_logs
for select 
using (auth.uid() = user_id);

create policy "select_public_conversion_rules" 
on billing.credit_conversion_rules
for select 
using (true);

-- ====================================================================
-- 8. GLOBAL HEALTH MONITORING UTILITY
-- ====================================================================

create or replace function public.get_public_pool_health()
returns text as $$
declare
  v_pool_balance integer;
begin
  select coalesce(balance, 0) into v_pool_balance 
  from public.credit_balances 
  where user_id is null;

  if v_pool_balance >= 10000 then return 'Healthy';
  elsif v_pool_balance >= 2500 then return 'Low';
  elsif v_pool_balance > 0 then return 'Critical';
  else return 'Empty';
  end if;
end;
$$ language plpgsql security definer;

-- ====================================================================
-- 9. INITIALIZATIONS
-- ====================================================================

INSERT INTO "public"."credit_balances" ("id", "user_id", "balance") VALUES ('00000000-0000-0000-0000-000000000000', null, 0) ON CONFLICT DO NOTHING;


-- To fully automate this, configure a daily execution rule via pg_cron extension:
-- select cron.schedule('0 2 * * *', 'select billing.process_expired_credits();');

-- insert into billing.credit_conversion_rules (currency, private_credits_per_unit, public_credits_per_unit)
-- values ('eur', 20.0, 10.0)
-- on conflict (currency) do update 
-- set private_credits_per_unit = excluded.private_credits_per_unit,
--     public_credits_per_unit = excluded.public_credits_per_unit;

-- select public.consume_credits('user-uuid-here', 5, 'recipe_import', '{"recipe_url": "https://..."}');