/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicCleanupLevelSchema = z.union([
  z.literal("none"),
  z.literal("low"),
  z.literal("medium"),
  z.literal("high"),
]);

export const publicCommonlyUsedLevelSchema = z.union([
  z.literal("daily"),
  z.literal("common"),
  z.literal("occasionally"),
  z.literal("rare"),
  z.literal("never"),
]);

export const publicCostLevelSchema = z.union([
  z.literal("minimal"),
  z.literal("budget"),
  z.literal("average"),
  z.literal("premium"),
]);

export const publicCourseSchema = z.union([
  z.literal("appetizer"),
  z.literal("main"),
  z.literal("side"),
  z.literal("prep"),
  z.literal("salad"),
  z.literal("soup"),
  z.literal("dessert"),
  z.literal("snack"),
  z.literal("drink"),
]);

export const publicCuisineSchema = z.union([
  z.literal("italian"),
  z.literal("mexican"),
  z.literal("indian"),
  z.literal("chinese"),
  z.literal("french"),
  z.literal("japanese"),
  z.literal("mediterranean"),
  z.literal("american"),
  z.literal("spanish"),
  z.literal("thai"),
  z.literal("greek"),
  z.literal("korean"),
  z.literal("vietnamese"),
  z.literal("middleeast"),
  z.literal("british"),
  z.literal("brazilian"),
  z.literal("caribbean"),
  z.literal("african"),
]);

export const publicEffortLevelSchema = z.union([
  z.literal("none"),
  z.literal("low"),
  z.literal("medium"),
  z.literal("high"),
]);

export const publicIngredientBaseUnitSchema = z.union([
  z.literal("g"),
  z.literal("ml"),
  z.literal("unit"),
]);

export const publicIngredientSubstitutionStrengthSchema = z.union([
  z.literal("equivalent"),
  z.literal("close"),
  z.literal("far"),
  z.literal("variant"),
]);

export const publicRecipeSourceTypeSchema = z.union([
  z.literal("website"),
  z.literal("user-manual"),
]);

export const publicRecipeToolSchema = z.union([
  z.literal("blender"),
  z.literal("fryer"),
  z.literal("juicer"),
  z.literal("kettle"),
  z.literal("microwave"),
  z.literal("mixer"),
  z.literal("oven"),
  z.literal("scale"),
  z.literal("stove"),
  z.literal("toaster"),
]);

export const publicSkillLevelSchema = z.union([
  z.literal("beginner"),
  z.literal("intermediate"),
  z.literal("advanced"),
  z.literal("chef"),
]);

export const publicSupermarketAisleSchema = z.union([
  z.literal("beverages"),
  z.literal("bread-pastries"),
  z.literal("care-health"),
  z.literal("frozen-convenience"),
  z.literal("fruits-vegetables"),
  z.literal("grain-products"),
  z.literal("home-garden"),
  z.literal("household"),
  z.literal("ingredients-spices"),
  z.literal("meat-fish"),
  z.literal("milk-cheese"),
  z.literal("pet-supplies"),
  z.literal("snacks-sweets"),
  z.literal("unknown"),
]);

export const publicTimeOfDaySchema = z.union([
  z.literal("breakfast"),
  z.literal("brunch"),
  z.literal("lunch"),
  z.literal("dinner"),
  z.literal("dessert"),
  z.literal("snack"),
  z.literal("drinks"),
]);

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const graphqlPublicGraphqlArgsSchema = z.object({
  extensions: jsonSchema.optional(),
  operationName: z.string().optional(),
  query: z.string().optional(),
  variables: jsonSchema.optional(),
});

export const graphqlPublicGraphqlReturnsSchema = jsonSchema;

export const publicIngredientSubstitutionsRowSchema = z.object({
  id: z.string(),
  original_ingredient_id: z.string(),
  original_to_substitute_ratio: z.number(),
  strength: publicIngredientSubstitutionStrengthSchema,
  substitute_ingredient_id: z.string(),
});

export const publicIngredientSubstitutionsInsertSchema = z.object({
  id: z.string().optional(),
  original_ingredient_id: z.string(),
  original_to_substitute_ratio: z.number().optional(),
  strength: publicIngredientSubstitutionStrengthSchema,
  substitute_ingredient_id: z.string(),
});

export const publicIngredientSubstitutionsUpdateSchema = z.object({
  id: z.string().optional(),
  original_ingredient_id: z.string().optional(),
  original_to_substitute_ratio: z.number().optional(),
  strength: publicIngredientSubstitutionStrengthSchema.optional(),
  substitute_ingredient_id: z.string().optional(),
});

export const publicIngredientSubstitutionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "ingredient_substitutions_original_ingredient_id_fkey",
    ),
    columns: z.tuple([z.literal("original_ingredient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("ingredients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal(
      "ingredient_substitutions_substitute_ingredient_id_fkey",
    ),
    columns: z.tuple([z.literal("substitute_ingredient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("ingredients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicIngredientTranslationsRowSchema = z.object({
  commonly_used: publicCommonlyUsedLevelSchema,
  fts: z.unknown(),
  ingredient_id: z.string(),
  language_id: z.number(),
  name_general: z.string(),
  name_plural: z.string().nullable(),
  name_singular: z.string().nullable(),
});

export const publicIngredientTranslationsInsertSchema = z.object({
  commonly_used: publicCommonlyUsedLevelSchema.optional(),
  fts: z.unknown().optional(),
  ingredient_id: z.string(),
  language_id: z.number(),
  name_general: z.string(),
  name_plural: z.string().optional().nullable(),
  name_singular: z.string().optional().nullable(),
});

export const publicIngredientTranslationsUpdateSchema = z.object({
  commonly_used: publicCommonlyUsedLevelSchema.optional(),
  fts: z.unknown().optional(),
  ingredient_id: z.string().optional(),
  language_id: z.number().optional(),
  name_general: z.string().optional(),
  name_plural: z.string().optional().nullable(),
  name_singular: z.string().optional().nullable(),
});

export const publicIngredientTranslationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("ingredient_translations_ingredient_id_fkey"),
    columns: z.tuple([z.literal("ingredient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("ingredients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("ingredient_translations_language_id_fkey"),
    columns: z.tuple([z.literal("language_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("languages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicIngredientsRowSchema = z.object({
  aisle: publicSupermarketAisleSchema.nullable(),
  base_unit: publicIngredientBaseUnitSchema,
  embedding: z.string().nullable(),
  g_per_ml: z.number().nullable(),
  g_per_unit: jsonSchema.nullable(),
  hierarchy: z.array(z.string()),
  id: z.string(),
  slug: z.string(),
  slug_general: z.string(),
  unit_frequencies: jsonSchema.nullable(),
});

export const publicIngredientsInsertSchema = z.object({
  aisle: publicSupermarketAisleSchema.optional().nullable(),
  base_unit: publicIngredientBaseUnitSchema,
  embedding: z.string().optional().nullable(),
  g_per_ml: z.number().optional().nullable(),
  g_per_unit: jsonSchema.optional().nullable(),
  hierarchy: z.array(z.string()),
  id: z.string().optional(),
  slug: z.string(),
  slug_general: z.string(),
  unit_frequencies: jsonSchema.optional().nullable(),
});

export const publicIngredientsUpdateSchema = z.object({
  aisle: publicSupermarketAisleSchema.optional().nullable(),
  base_unit: publicIngredientBaseUnitSchema.optional(),
  embedding: z.string().optional().nullable(),
  g_per_ml: z.number().optional().nullable(),
  g_per_unit: jsonSchema.optional().nullable(),
  hierarchy: z.array(z.string()).optional(),
  id: z.string().optional(),
  slug: z.string().optional(),
  slug_general: z.string().optional(),
  unit_frequencies: jsonSchema.optional().nullable(),
});

export const publicLanguagesRowSchema = z.object({
  code: z.string(),
  country_en: z.string(),
  country_local: z.string(),
  emoji: z.string().nullable(),
  id: z.number(),
  lang: z.string(),
  name_en: z.string(),
  name_local: z.string(),
});

export const publicLanguagesInsertSchema = z.object({
  code: z.string(),
  country_en: z.string(),
  country_local: z.string(),
  emoji: z.string().optional().nullable(),
  id: z.number().optional(),
  lang: z.string(),
  name_en: z.string(),
  name_local: z.string(),
});

export const publicLanguagesUpdateSchema = z.object({
  code: z.string().optional(),
  country_en: z.string().optional(),
  country_local: z.string().optional(),
  emoji: z.string().optional().nullable(),
  id: z.number().optional(),
  lang: z.string().optional(),
  name_en: z.string().optional(),
  name_local: z.string().optional(),
});

export const publicRecipeIngredientsRowSchema = z.object({
  details: z.string().nullable(),
  ingredient_id: z.string(),
  is_optional: z.boolean(),
  notes: z.string().nullable(),
  preparation: z.string().nullable(),
  quantity: z.number().nullable(),
  raw_input: z.string(),
  recipe_id: z.string(),
  unit: z.string().nullable(),
});

export const publicRecipeIngredientsInsertSchema = z.object({
  details: z.string().optional().nullable(),
  ingredient_id: z.string(),
  is_optional: z.boolean().optional(),
  notes: z.string().optional().nullable(),
  preparation: z.string().optional().nullable(),
  quantity: z.number().optional().nullable(),
  raw_input: z.string(),
  recipe_id: z.string(),
  unit: z.string().optional().nullable(),
});

export const publicRecipeIngredientsUpdateSchema = z.object({
  details: z.string().optional().nullable(),
  ingredient_id: z.string().optional(),
  is_optional: z.boolean().optional(),
  notes: z.string().optional().nullable(),
  preparation: z.string().optional().nullable(),
  quantity: z.number().optional().nullable(),
  raw_input: z.string().optional(),
  recipe_id: z.string().optional(),
  unit: z.string().optional().nullable(),
});

export const publicRecipeIngredientsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("recipe_ingredients_ingredient_id_fkey"),
    columns: z.tuple([z.literal("ingredient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("ingredients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("recipe_ingredients_recipe_id_fkey"),
    columns: z.tuple([z.literal("recipe_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("recipes"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicRecipesRowSchema = z.object({
  author_id: z.string(),
  cleanup_level: publicCleanupLevelSchema,
  cost_level: publicCostLevelSchema,
  courses: z.array(publicCourseSchema),
  created_at: z.string(),
  cuisines: z.array(publicCuisineSchema),
  description: z.string().nullable(),
  effort_level: publicEffortLevelSchema,
  id: z.string(),
  image_ids: z.array(z.string()).nullable(),
  language_id: z.number(),
  notes: z.string().nullable(),
  search_term: z.string().nullable(),
  servings: z.number(),
  skill_level: publicSkillLevelSchema,
  slug: z.string(),
  source_type: publicRecipeSourceTypeSchema,
  source_url: z.string().nullable(),
  steps: z.array(z.string()).nullable(),
  time_cook_minutes: z.number().nullable(),
  time_prep_minutes: z.number().nullable(),
  time_rest_minutes: z.number().nullable(),
  time_total_minutes: z.number().nullable(),
  times_of_day: z.array(publicTimeOfDaySchema),
  title: z.string(),
  tools: z.array(publicRecipeToolSchema),
  updated_at: z.string(),
});

export const publicRecipesInsertSchema = z.object({
  author_id: z.string(),
  cleanup_level: publicCleanupLevelSchema,
  cost_level: publicCostLevelSchema,
  courses: z.array(publicCourseSchema),
  created_at: z.string().optional(),
  cuisines: z.array(publicCuisineSchema),
  description: z.string().optional().nullable(),
  effort_level: publicEffortLevelSchema,
  id: z.string().optional(),
  image_ids: z.array(z.string()).optional().nullable(),
  language_id: z.number(),
  notes: z.string().optional().nullable(),
  search_term: z.string().optional().nullable(),
  servings: z.number(),
  skill_level: publicSkillLevelSchema,
  slug: z.string(),
  source_type: publicRecipeSourceTypeSchema,
  source_url: z.string().optional().nullable(),
  steps: z.array(z.string()).optional().nullable(),
  time_cook_minutes: z.number().optional().nullable(),
  time_prep_minutes: z.number().optional().nullable(),
  time_rest_minutes: z.number().optional().nullable(),
  time_total_minutes: z.number().optional().nullable(),
  times_of_day: z.array(publicTimeOfDaySchema),
  title: z.string(),
  tools: z.array(publicRecipeToolSchema),
  updated_at: z.string().optional(),
});

export const publicRecipesUpdateSchema = z.object({
  author_id: z.string().optional(),
  cleanup_level: publicCleanupLevelSchema.optional(),
  cost_level: publicCostLevelSchema.optional(),
  courses: z.array(publicCourseSchema).optional(),
  created_at: z.string().optional(),
  cuisines: z.array(publicCuisineSchema).optional(),
  description: z.string().optional().nullable(),
  effort_level: publicEffortLevelSchema.optional(),
  id: z.string().optional(),
  image_ids: z.array(z.string()).optional().nullable(),
  language_id: z.number().optional(),
  notes: z.string().optional().nullable(),
  search_term: z.string().optional().nullable(),
  servings: z.number().optional(),
  skill_level: publicSkillLevelSchema.optional(),
  slug: z.string().optional(),
  source_type: publicRecipeSourceTypeSchema.optional(),
  source_url: z.string().optional().nullable(),
  steps: z.array(z.string()).optional().nullable(),
  time_cook_minutes: z.number().optional().nullable(),
  time_prep_minutes: z.number().optional().nullable(),
  time_rest_minutes: z.number().optional().nullable(),
  time_total_minutes: z.number().optional().nullable(),
  times_of_day: z.array(publicTimeOfDaySchema).optional(),
  title: z.string().optional(),
  tools: z.array(publicRecipeToolSchema).optional(),
  updated_at: z.string().optional(),
});

export const publicRecipesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("recipes_language_id_fkey"),
    columns: z.tuple([z.literal("language_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("languages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicSpaceMembersRowSchema = z.object({
  created_at: z.string(),
  space_id: z.string(),
  theme: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicSpaceMembersInsertSchema = z.object({
  created_at: z.string().optional(),
  space_id: z.string(),
  theme: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicSpaceMembersUpdateSchema = z.object({
  created_at: z.string().optional(),
  space_id: z.string().optional(),
  theme: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicSpaceMembersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("space_members_space_id_fkey"),
    columns: z.tuple([z.literal("space_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("spaces"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicSpacePlanMealsRowSchema = z.object({
  created_at: z.string().nullable(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  position: z.number(),
  recipe_id: z.string(),
  servings: z.number(),
  space_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicSpacePlanMealsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  position: z.number().optional(),
  recipe_id: z.string(),
  servings: z.number().optional(),
  space_id: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const publicSpacePlanMealsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  position: z.number().optional(),
  recipe_id: z.string().optional(),
  servings: z.number().optional(),
  space_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicSpacePlanMealsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("space_plan_meals_recipe_id_fkey"),
    columns: z.tuple([z.literal("recipe_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("recipes"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("space_plan_meals_space_id_fkey"),
    columns: z.tuple([z.literal("space_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("spaces"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicSpacePlanShoppingListsRowSchema = z.object({
  checked_at: z.string().nullable(),
  created_at: z.string().nullable(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  ingredient_id: z.string().nullable(),
  meal_id: z.string().nullable(),
  meal_origin: z.string().nullable(),
  name: z.string().nullable(),
  quantity: z.number().nullable(),
  space_id: z.string(),
  type: z.string(),
  unit: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicSpacePlanShoppingListsInsertSchema = z.object({
  checked_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ingredient_id: z.string().optional().nullable(),
  meal_id: z.string().optional().nullable(),
  meal_origin: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  quantity: z.number().optional().nullable(),
  space_id: z.string(),
  type: z.string(),
  unit: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicSpacePlanShoppingListsUpdateSchema = z.object({
  checked_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ingredient_id: z.string().optional().nullable(),
  meal_id: z.string().optional().nullable(),
  meal_origin: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  quantity: z.number().optional().nullable(),
  space_id: z.string().optional(),
  type: z.string().optional(),
  unit: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicSpacePlanShoppingListsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("space_plan_shopping_lists_ingredient_id_fkey"),
    columns: z.tuple([z.literal("ingredient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("ingredients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("space_plan_shopping_lists_meal_id_fkey"),
    columns: z.tuple([z.literal("meal_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("space_plan_meals"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("space_plan_shopping_lists_space_id_fkey"),
    columns: z.tuple([z.literal("space_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("spaces"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicSpacesRowSchema = z.object({
  author_id: z.string(),
  created_at: z.string(),
  icon: z.string(),
  id: z.string(),
  initial_theme: z.string(),
  locale: z.string(),
  name: z.string(),
  updated_at: z.string(),
});

export const publicSpacesInsertSchema = z.object({
  author_id: z.string(),
  created_at: z.string().optional(),
  icon: z.string(),
  id: z.string().optional(),
  initial_theme: z.string(),
  locale: z.string(),
  name: z.string(),
  updated_at: z.string().optional(),
});

export const publicSpacesUpdateSchema = z.object({
  author_id: z.string().optional(),
  created_at: z.string().optional(),
  icon: z.string().optional(),
  id: z.string().optional(),
  initial_theme: z.string().optional(),
  locale: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicUserPreferencesRowSchema = z.object({
  created_at: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  onboarding_status: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicUserPreferencesInsertSchema = z.object({
  created_at: z.string().optional(),
  first_name: z.string(),
  last_name: z.string(),
  onboarding_status: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicUserPreferencesUpdateSchema = z.object({
  created_at: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  onboarding_status: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserPublicProfilesRowSchema = z.object({
  created_at: z.string(),
  icon: z.string(),
  image_url: z.string().nullable(),
  updated_at: z.string(),
  user_id: z.string(),
  user_name: z.string(),
});

export const publicUserPublicProfilesInsertSchema = z.object({
  created_at: z.string().optional(),
  icon: z.string(),
  image_url: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  user_name: z.string(),
});

export const publicUserPublicProfilesUpdateSchema = z.object({
  created_at: z.string().optional(),
  icon: z.string().optional(),
  image_url: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  user_name: z.string().optional(),
});

export const publicMatchIngredientArgsSchema = z.object({
  is_raw_import: z.boolean().optional(),
  lang_code: z.string(),
  n_matches: z.number().optional(),
  query_text: z.string(),
});

export const publicMatchIngredientReturnsSchema = z.array(
  z.object({
    aisle: publicSupermarketAisleSchema.nullable(),
    base_unit: publicIngredientBaseUnitSchema,
    embedding: z.string().nullable(),
    g_per_ml: z.number().nullable(),
    g_per_unit: jsonSchema.nullable(),
    hierarchy: z.array(z.string()),
    id: z.string(),
    slug: z.string(),
    slug_general: z.string(),
    unit_frequencies: jsonSchema.nullable(),
  }),
);

export const publicShowLimitArgsSchema = z.never();

export const publicShowLimitReturnsSchema = z.number();

export const publicShowTrgmArgsSchema = z.object({
  "": z.string(),
});

export const publicShowTrgmReturnsSchema = z.array(z.string());

export const publicSlugifyArgsSchema = z.object({
  max_length: z.number().optional(),
  value: z.string(),
});

export const publicSlugifyReturnsSchema = z.string();

export const publicUnaccentArgsSchema = z.object({
  "": z.string(),
});

export const publicUnaccentReturnsSchema = z.string();

export type PublicCleanupLevel = z.infer<typeof publicCleanupLevelSchema>;
export type PublicCommonlyUsedLevel = z.infer<
  typeof publicCommonlyUsedLevelSchema
>;
export type PublicCostLevel = z.infer<typeof publicCostLevelSchema>;
export type PublicCourse = z.infer<typeof publicCourseSchema>;
export type PublicCuisine = z.infer<typeof publicCuisineSchema>;
export type PublicEffortLevel = z.infer<typeof publicEffortLevelSchema>;
export type PublicIngredientBaseUnit = z.infer<
  typeof publicIngredientBaseUnitSchema
>;
export type PublicIngredientSubstitutionStrength = z.infer<
  typeof publicIngredientSubstitutionStrengthSchema
>;
export type PublicRecipeSourceType = z.infer<
  typeof publicRecipeSourceTypeSchema
>;
export type PublicRecipeTool = z.infer<typeof publicRecipeToolSchema>;
export type PublicSkillLevel = z.infer<typeof publicSkillLevelSchema>;
export type PublicSupermarketAisle = z.infer<
  typeof publicSupermarketAisleSchema
>;
export type PublicTimeOfDay = z.infer<typeof publicTimeOfDaySchema>;
export type Json = z.infer<typeof jsonSchema>;
export type GraphqlPublicGraphqlArgs = z.infer<
  typeof graphqlPublicGraphqlArgsSchema
>;
export type GraphqlPublicGraphqlReturns = z.infer<
  typeof graphqlPublicGraphqlReturnsSchema
>;
export type PublicIngredientSubstitutionsRow = z.infer<
  typeof publicIngredientSubstitutionsRowSchema
>;
export type PublicIngredientSubstitutionsInsert = z.infer<
  typeof publicIngredientSubstitutionsInsertSchema
>;
export type PublicIngredientSubstitutionsUpdate = z.infer<
  typeof publicIngredientSubstitutionsUpdateSchema
>;
export type PublicIngredientSubstitutionsRelationships = z.infer<
  typeof publicIngredientSubstitutionsRelationshipsSchema
>;
export type PublicIngredientTranslationsRow = z.infer<
  typeof publicIngredientTranslationsRowSchema
>;
export type PublicIngredientTranslationsInsert = z.infer<
  typeof publicIngredientTranslationsInsertSchema
>;
export type PublicIngredientTranslationsUpdate = z.infer<
  typeof publicIngredientTranslationsUpdateSchema
>;
export type PublicIngredientTranslationsRelationships = z.infer<
  typeof publicIngredientTranslationsRelationshipsSchema
>;
export type PublicIngredientsRow = z.infer<typeof publicIngredientsRowSchema>;
export type PublicIngredientsInsert = z.infer<
  typeof publicIngredientsInsertSchema
>;
export type PublicIngredientsUpdate = z.infer<
  typeof publicIngredientsUpdateSchema
>;
export type PublicLanguagesRow = z.infer<typeof publicLanguagesRowSchema>;
export type PublicLanguagesInsert = z.infer<typeof publicLanguagesInsertSchema>;
export type PublicLanguagesUpdate = z.infer<typeof publicLanguagesUpdateSchema>;
export type PublicRecipeIngredientsRow = z.infer<
  typeof publicRecipeIngredientsRowSchema
>;
export type PublicRecipeIngredientsInsert = z.infer<
  typeof publicRecipeIngredientsInsertSchema
>;
export type PublicRecipeIngredientsUpdate = z.infer<
  typeof publicRecipeIngredientsUpdateSchema
>;
export type PublicRecipeIngredientsRelationships = z.infer<
  typeof publicRecipeIngredientsRelationshipsSchema
>;
export type PublicRecipesRow = z.infer<typeof publicRecipesRowSchema>;
export type PublicRecipesInsert = z.infer<typeof publicRecipesInsertSchema>;
export type PublicRecipesUpdate = z.infer<typeof publicRecipesUpdateSchema>;
export type PublicRecipesRelationships = z.infer<
  typeof publicRecipesRelationshipsSchema
>;
export type PublicSpaceMembersRow = z.infer<typeof publicSpaceMembersRowSchema>;
export type PublicSpaceMembersInsert = z.infer<
  typeof publicSpaceMembersInsertSchema
>;
export type PublicSpaceMembersUpdate = z.infer<
  typeof publicSpaceMembersUpdateSchema
>;
export type PublicSpaceMembersRelationships = z.infer<
  typeof publicSpaceMembersRelationshipsSchema
>;
export type PublicSpacePlanMealsRow = z.infer<
  typeof publicSpacePlanMealsRowSchema
>;
export type PublicSpacePlanMealsInsert = z.infer<
  typeof publicSpacePlanMealsInsertSchema
>;
export type PublicSpacePlanMealsUpdate = z.infer<
  typeof publicSpacePlanMealsUpdateSchema
>;
export type PublicSpacePlanMealsRelationships = z.infer<
  typeof publicSpacePlanMealsRelationshipsSchema
>;
export type PublicSpacePlanShoppingListsRow = z.infer<
  typeof publicSpacePlanShoppingListsRowSchema
>;
export type PublicSpacePlanShoppingListsInsert = z.infer<
  typeof publicSpacePlanShoppingListsInsertSchema
>;
export type PublicSpacePlanShoppingListsUpdate = z.infer<
  typeof publicSpacePlanShoppingListsUpdateSchema
>;
export type PublicSpacePlanShoppingListsRelationships = z.infer<
  typeof publicSpacePlanShoppingListsRelationshipsSchema
>;
export type PublicSpacesRow = z.infer<typeof publicSpacesRowSchema>;
export type PublicSpacesInsert = z.infer<typeof publicSpacesInsertSchema>;
export type PublicSpacesUpdate = z.infer<typeof publicSpacesUpdateSchema>;
export type PublicUserPreferencesRow = z.infer<
  typeof publicUserPreferencesRowSchema
>;
export type PublicUserPreferencesInsert = z.infer<
  typeof publicUserPreferencesInsertSchema
>;
export type PublicUserPreferencesUpdate = z.infer<
  typeof publicUserPreferencesUpdateSchema
>;
export type PublicUserPublicProfilesRow = z.infer<
  typeof publicUserPublicProfilesRowSchema
>;
export type PublicUserPublicProfilesInsert = z.infer<
  typeof publicUserPublicProfilesInsertSchema
>;
export type PublicUserPublicProfilesUpdate = z.infer<
  typeof publicUserPublicProfilesUpdateSchema
>;
export type PublicMatchIngredientArgs = z.infer<
  typeof publicMatchIngredientArgsSchema
>;
export type PublicMatchIngredientReturns = z.infer<
  typeof publicMatchIngredientReturnsSchema
>;
export type PublicShowLimitArgs = z.infer<typeof publicShowLimitArgsSchema>;
export type PublicShowLimitReturns = z.infer<
  typeof publicShowLimitReturnsSchema
>;
export type PublicShowTrgmArgs = z.infer<typeof publicShowTrgmArgsSchema>;
export type PublicShowTrgmReturns = z.infer<typeof publicShowTrgmReturnsSchema>;
export type PublicSlugifyArgs = z.infer<typeof publicSlugifyArgsSchema>;
export type PublicSlugifyReturns = z.infer<typeof publicSlugifyReturnsSchema>;
export type PublicUnaccentArgs = z.infer<typeof publicUnaccentArgsSchema>;
export type PublicUnaccentReturns = z.infer<typeof publicUnaccentReturnsSchema>;
