import { z } from 'zod';

import { languageKeySchema, type LanguageKey } from '$lib/features/user-settings/consts';
import type { Database } from '$lib/shared/db/supabase.types';
import { publicRecipeSourceTypeSchema } from '$lib/shared/db/supazod.schemas';

import { OpError } from '../errors.js';
import { defineOp } from '../registry.js';
import { getLanguageId } from './get-language-id-helper.js';

export const createDraftRecipeInput = z.object({
	sourceType: publicRecipeSourceTypeSchema,
	lang: languageKeySchema,
	title: z.string().min(2)
});

export type CreateDraftRecipeInput = z.infer<typeof createDraftRecipeInput>;

/**
 * Creates an empty draft recipe owned by the caller.
 * Moved from `features/recipes/actions/create-draft-recipe.remote.ts`
 * (toast stays in the UI; throws instead of returning `undefined`).
 */
export const createDraftRecipeOp = defineOp({
	name: 'recipes.create-draft',
	domain: 'recipes',
	kind: 'write',
	sync: 'synced',
	input: createDraftRecipeInput,
	handler: async (ctx, { sourceType, lang, title }) => {
		// The remote required a confirmed (non-anonymous) email. Server remotes
		// still enforce this via `requireCtx`, but synced ops can also run from
		// the browser — keep the check here so both paths behave identically.
		const {
			data: { user }
		} = await ctx.supabase.auth.getUser();
		if (
			!user ||
			user.role !== 'authenticated' ||
			user.is_anonymous ||
			!user.email ||
			!user.confirmed_at
		) {
			throw new OpError('UNAUTHENTICATED', 'User must be confirmed with a valid email.');
		}

		// Use the space's language as fallback if the LLM doesn't guess it from the recipe later
		const { data: languageData } = await getLanguageId(ctx.supabase, lang as LanguageKey);
		if (!languageData) throw new OpError('VALIDATION', 'Could not retrieve language ID.');

		// Create an empty recipe
		const { data: recipeIdData, error: recipeIdError } = await ctx.supabase
			.from('recipes')
			.insert([
				{
					// ID will be generated by the database
					created_at: new Date().toISOString(),
					updated_at: new Date().toISOString(),

					// Source
					source_type: sourceType,

					// General info
					title: title || 'New Recipe',
					short_title: (title || 'Unknown').split(' ')?.[0] || 'Unknown',
					description: '',
					notes: '',
					author_id: ctx.userId,
					language_id: languageData.id,
					image_ids: [],
					slug: '', // Will be generated by a db trigger

					// Filters (single select enums)
					cleanup_level: 'none',
					cost_level: 'budget',
					effort_level: 'low',
					skill_level: 'beginner',

					// Filters (multi select enums)
					courses: ['main'],
					cuisines: [],
					times_of_day: [],
					tools: [],

					// Cook times
					time_prep_minutes: 0,
					time_cook_minutes: 0,
					time_rest_minutes: 0,

					// Servings (ingredients will be inserted in another table)
					servings: 4,

					// Steps
					steps: []
				} as Database['public']['Tables']['recipes']['Insert']
			])
			.select('id')
			.single();

		if (recipeIdError || !recipeIdData) {
			throw new OpError('INTERNAL', 'Failed to create recipe.', recipeIdError);
		}

		return recipeIdData.id as Database['public']['Tables']['recipes']['Row']['id'];
	}
});
