import { z } from 'zod';

import { createRecipeFormSchema } from '$lib/features/recipes/models/schemas';
import type { Tables, TablesInsert } from '$lib/shared/db/supabase.types';

import { OpError } from '../errors.js';
import { resolveLanguageId } from '../languages/resolve.js';
import { defineOp } from '../registry.js';

export const editRecipeInput = z.object({
	/** Null when creating a new recipe (the edit page id `new`). */
	recipeId: z.string().nullable().default(null),
	data: createRecipeFormSchema
});

export type EditRecipeInput = z.infer<typeof editRecipeInput>;

export type EditRecipeOutput = { id: string };

/**
 * Creates a recipe (upsert) and replaces its ingredients (delete + re-insert).
 * NEW extraction from `routes/(app)/recipes/[id]/edit/+page.svelte:onSubmit`
 * (toast/goto stay in the page; throws instead of early-returning).
 */
export const editRecipeOp = defineOp({
	name: 'recipes.edit',
	domain: 'recipes',
	kind: 'write',
	sync: 'synced',
	docs: {
		title: 'Edit recipe',
		description: 'Creates or updates a recipe and replaces its ingredients.'
	},
	input: editRecipeInput,
	handler: async (ctx, { recipeId, data }) => {
		const { id: languageId } = await resolveLanguageId(ctx.supabase, data.lang);

		// Create the recipe
		const { data: recipeIdData, error: recipeIdError } = await ctx.supabase
			.from('recipes')
			.upsert({
				// ID if we are updating an existing recipe
				id: recipeId ?? undefined,

				// Source
				source_type: data.source_type,
				source_url: data.source_type === 'user-manual' ? null : data.source_url,

				// General info
				title: data.title,
				short_title: data.short_title,
				description: data.description,
				notes: '',
				author_id: ctx.userId,
				language_id: languageId,
				slug: '', // Will be generated by a db trigger

				// Filters (single select enums)
				cleanup_level: data.cleanupLevel,
				cost_level: data.costLevel,
				effort_level: data.effortLevel,
				skill_level: data.skillLevel,

				// Multi-select filters
				times_of_day: data.timesofday_ids,
				courses: data.course_ids,
				cuisines: data.cuisine_ids,
				// tags: data.tag_ids, // TODO revisit
				tools: data.tool_ids,

				// Cook times
				time_prep_minutes: data.timePrep,
				time_cook_minutes: data.timeCook,
				time_rest_minutes: data.timeRest,

				// Servings (ingredients will be inserted in another table)
				servings: data.servings,

				// Steps
				steps: data.stepDescriptions
			} as Tables<'recipes'>)
			.select('id')
			.single();

		if (recipeIdError || !recipeIdData) {
			throw new OpError('INTERNAL', 'Failed to create recipe.', recipeIdError);
		}

		// If it's an existing recipe, we need to delete the old ingredients first
		if (recipeId) {
			const { error: deleteError } = await ctx.supabase
				.from('recipe_ingredients')
				.delete()
				.eq('recipe_id', recipeId);

			if (deleteError) {
				throw new OpError('INTERNAL', 'Failed to delete old ingredients.', deleteError);
			}
		}

		// Add the ingredients to the recipe_ingredients table
		const { error: ingredientsError } = await ctx.supabase
			.from('recipe_ingredients')
			.insert(
				data.ingredientIds.map(
					(id, i) =>
						({
							raw_input: data.ingredientRawInputs[i],
							recipe_id: recipeIdData.id,
							ingredient_id: id,
							custom_name: data.ingredientCustomNames[i],
							quantity: data.ingredientAmounts[i],
							unit: data.ingredientUnits[i],
							details: data.ingredientDetails[i],
							notes: data.ingredientNotes[i],
							preparation: data.ingredientPreparations[i],
							is_optional: data.ingredientIsOptional[i]
						}) satisfies TablesInsert<'recipe_ingredients'>
				)
			)
			.select();

		if (ingredientsError) {
			throw new OpError('INTERNAL', 'Failed to add ingredients.', ingredientsError);
		}

		return { id: recipeIdData.id };
	}
});
