import { supabase } from '$lib/shared/db/supabase-client';
import type { Database } from '$lib/shared/db/supabase.types';
import { toast } from 'svelte-sonner';

export async function createDraftRecipe(
	sourceType: 'user-manual' | 'website',
	lang: string = 'fr-FR'
): Promise<Database['public']['Tables']['recipes']['Row']['id'] | undefined> {
	// Get the language ID
	const { data: langData, error: langError } = await supabase
		.from('languages')
		.select('id')
		.eq('lang', lang)
		.single();

	if (langError || !langData) {
		console.error('Error fetching language ID:', langError);
		toast.error('Failed to fetch language ID.');
		return;
	}

	// Create an empty recipe
	const { data: recipeIdData, error: recipeIdError } = await supabase
		.from('recipes')
		.insert([
			{
				// ID will be generated by the database
				created_at: new Date().toISOString(),
				updated_at: new Date().toISOString(),

				// Source
				source_type: sourceType,

				// General info
				title: '',
				description: '',
				notes: '',
				author_id: '01b12743-d908-46ff-b239-332438cb4c4d', // TODO connect auth
				language_id: langData.id,
				image_ids: [],
				slug: '', // Will be generated by a db trigger

				// Filters (single select enums)
				cleanup_level: 'none',
				cost_level: 'budget',
				effort_level: 'low',
				skill_level: 'beginner',

				// Cook times
				time_prep_minutes: 0,
				time_cook_minutes: 0,
				time_rest_minutes: 0,

				// Servings (ingredients will be inserted in another table)
				servings: 4,

				// Steps
				steps: []
			}
		])
		.select('id')
		.single();

	if (recipeIdError || !recipeIdData) {
		console.error('Error creating recipe:', recipeIdError);
		toast.error('Failed to create recipe.');
		return;
	}

	return recipeIdData.id as Database['public']['Tables']['recipes']['Row']['id'];
}
