import { userState } from '$lib/features/auth/state/user-state.svelte';
import { supabase } from '$lib/shared/db/supabase-client.svelte';
import type { Database } from '$lib/shared/db/supabase.types';
import { toast } from 'svelte-sonner';

export async function createDraftRecipe(
	sourceType: 'user-manual' | 'website',
	languageId: number,
	title: string = ''
): Promise<Database['public']['Tables']['recipes']['Row']['id'] | undefined> {
	if (!supabase.client) {
		console.error('Supabase client not available');
		return;
	}
	if (!userState.user) {
		console.error('User not authenticated');
		toast.error('You must be logged in to create a recipe.');
		return;
	}

	// Create an empty recipe
	const { data: recipeIdData, error: recipeIdError } = await supabase.client
		.from('recipes')
		.insert([
			{
				// ID will be generated by the database
				created_at: new Date().toISOString(),
				updated_at: new Date().toISOString(),

				// Source
				source_type: sourceType,

				// General info
				title: title || 'New Recipe',
				short_title: (title || 'Unknown').split(' ')?.[0] || 'Unknown',
				description: '',
				notes: '',
				author_id: userState.user.id,
				language_id: languageId,
				image_ids: [],
				slug: '', // Will be generated by a db trigger

				// Filters (single select enums)
				cleanup_level: 'none',
				cost_level: 'budget',
				effort_level: 'low',
				skill_level: 'beginner',

				// Filters (multi select enums)
				courses: ['main'],
				cuisines: [],
				times_of_day: [],
				tools: [],

				// Cook times
				time_prep_minutes: 0,
				time_cook_minutes: 0,
				time_rest_minutes: 0,

				// Servings (ingredients will be inserted in another table)
				servings: 4,

				// Steps
				steps: []
			} as Database['public']['Tables']['recipes']['Insert']
		])
		.select('id')
		.single();

	if (recipeIdError || !recipeIdData) {
		console.error('Error creating recipe:', recipeIdError);
		toast.error('Failed to create recipe.');
		return;
	}

	return recipeIdData.id as Database['public']['Tables']['recipes']['Row']['id'];
}
