import { getRequestEvent, query } from '$app/server';
import { serverIsUserAuthenticated } from '$lib/features/billing/server/utils/is-user-authenticated';
import { languageKeySchema, type LanguageKey } from '$lib/features/user-settings/consts';
import type { Database } from '$lib/shared/db/supabase.types';
import { publicRecipeSourceTypeSchema } from '$lib/shared/db/supazod.schemas';
import { toast } from 'svelte-sonner';
import z from 'zod';
import { getLanguageId } from '../queries/get-language-id';

export const createDraftRecipe = query(
	z.object({
		sourceType: publicRecipeSourceTypeSchema,
		lang: languageKeySchema,
		title: z.string().min(2)
	}),
	async ({ sourceType, lang, title }) => {
		console.log('Creating draft recipe', sourceType, lang, title);
		const event = getRequestEvent();
		const { userId, isValid } = await serverIsUserAuthenticated(event.locals.supabase);
		if (!isValid) throw new Error('User must be confirmed with a valid email.');

		// Use the space's language as fallback if the LLM doesn't guess it from the recipe later
		const { data: languageData } = await getLanguageId(event.locals.supabase, lang as LanguageKey);
		if (!languageData) throw new Error('Could not retrieve language ID.');

		// Create an empty recipe
		const { data: recipeIdData, error: recipeIdError } = await event.locals.supabase
			.from('recipes')
			.insert([
				{
					// ID will be generated by the database
					created_at: new Date().toISOString(),
					updated_at: new Date().toISOString(),

					// Source
					source_type: sourceType,

					// General info
					title: title || 'New Recipe',
					short_title: (title || 'Unknown').split(' ')?.[0] || 'Unknown',
					description: '',
					notes: '',
					author_id: userId,
					language_id: languageData.id,
					image_ids: [],
					slug: '', // Will be generated by a db trigger

					// Filters (single select enums)
					cleanup_level: 'none',
					cost_level: 'budget',
					effort_level: 'low',
					skill_level: 'beginner',

					// Filters (multi select enums)
					courses: ['main'],
					cuisines: [],
					times_of_day: [],
					tools: [],

					// Cook times
					time_prep_minutes: 0,
					time_cook_minutes: 0,
					time_rest_minutes: 0,

					// Servings (ingredients will be inserted in another table)
					servings: 4,

					// Steps
					steps: []
				} as Database['public']['Tables']['recipes']['Insert']
			])
			.select('id')
			.single();

		if (recipeIdError || !recipeIdData) {
			console.error('Error creating recipe:', recipeIdError);
			toast.error('Failed to create recipe.');
			return;
		}

		return recipeIdData.id as Database['public']['Tables']['recipes']['Row']['id'];
	}
);
